export const ADD_NEW_DOWNLOAD = 'ADD_NEW_DOWNLOAD';
export const CHANGE_DOWNLOAD_URL = 'CHANGE_DOWNLOAD_URL';
export const CHANGE_DOWNLOAD_INFO = 'CHANGE_DOWNLOAD_INFO';
export const UPDATE_BYTES_DOWNLOADED = 'UPDATE_BYTES_DOWNLOADED';
export const SET_DOWNLOAD_RES = 'SET_DOWNLOAD_RES';
export const GOT_DOWNLOAD_INFO = 'GOT_DOWNLOAD_INFO';
export const DOWNLOAD_PROGRESSING = 'DOWNLOAD_PROGRESSING';
export const PAUSE_DOWNLOAD = 'PAUSE_DOWNLOAD';
export const CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD';
export const COMPLETE_DOWNLOAD = 'COMPLETE_DOWNLOAD';
export const SHOW_DOWNLOAD_ERROR = 'SHOW_DOWNLOAD_ERROR';
export const SHOW_DOWNLOAD = 'SHOW_DOWNLOAD';
export const HIDE_DOWNLOAD = 'HIDE_DOWNLOAD';
export const DOWNLOAD_FILE_REMOVED = 'DOWNLOAD_FILE_REMOVED';
export const REMOVE_DOWNLOAD = 'REMOVE_DOWNLOAD';
export const TOGGLE_OPEN_WHEN_DONE = 'TOGGLE_OPEN_WHEN_DONE';

export const SET_INTERVAL = 'SET_INTERVAL';
export const SUBSCRIBE_TO_INTERVAL = 'SUBSCRIBE_TO_INTERVAL';
export const UNSUBSCRIBE_FROM_INTERVAL = 'UNSUBSCRIBE_FROM_INTERVAL';

export const NOTIFY = 'NOTIFY';

export const TOGGLE_SAVE_DATA = 'TOGGLE_SAVE_DATA';
