export const ADD_NEW_DOWNLOAD = 'ADD_NEW_DOWNLOAD';
export const CHANGE_DOWNLOAD_URL = 'CHANGE_DOWNLOAD_URL';
export const CHANGE_DOWNLOAD_INFO = 'CHANGE_DOWNLOAD_INFO';
export const UPDATE_BYTES_DOWNLOADED_SHOWN = 'UPDATE_BYTES_DOWNLOADED_SHOWN';
export const SET_DOWNLOAD_RES = 'SET_DOWNLOAD_RES';
export const GOT_DOWNLOAD_INFO = 'GOT_DOWNLOAD_INFO';
export const DOWNLOAD_PROGRESSING = 'DOWNLOAD_PROGRESSING';
export const PAUSE_DOWNLOAD = 'PAUSE_DOWNLOAD';
export const CANCEL_DOWNLOAD = 'CANCEL_DOWNLOAD';
export const COMPLETE_DOWNLOAD = 'COMPLETE_DOWNLOAD';
export const CHANGE_DOWNLOAD_SPEED = 'CHANGE_DOWNLOAD_SPEED';
export const SHOW_DOWNLOAD_ERROR = 'SHOW_DOWNLOAD_ERROR';
export const SHOW_DOWNLOAD = 'SHOW_DOWNLOAD';
export const HIDE_DOWNLOAD = 'HIDE_DOWNLOAD';
export const DOWNLOAD_FILE_REMOVED = 'DOWNLOAD_FILE_REMOVED';
export const REMOVE_DOWNLOAD = 'REMOVE_DOWNLOAD';
export const TOGGLE_OPEN_WHEN_DONE = 'TOGGLE_OPEN_WHEN_DONE';
export const CHANGE_DOWNLOAD_GROUP = 'CHANGE_DOWNLOAD_GROUP';
export const CHOSEN_YOUTUBE_FORMAT = 'CHOSEN_YOUTUBE_FORMAT';

export const NOTIFY = 'NOTIFY';

export const TOGGLE_SAVE_DATA = 'TOGGLE_SAVE_DATA';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const TOGGLE_ALWAYS_OPEN_DOWNLOADS_WHEN_DONE = 'TOGGLE_ALWAYS_OPEN_DOWNLOADS_WHEN_DONE';
export const TOGGLE_START_DOWNLOADS_AUTOMATICALLY = 'TOGGLE_START_DOWNLOADS_AUTOMATICALLY';
export const TOGGLE_LAUNCH_AT_STARTUP = 'TOGGLE_LAUNCH_AT_STARTUP';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const CHANGE_PAGE = 'CHANGE_PAGE';
